services: 
  postgres_db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web: 
    depends_on:
      - postgres_db
    build: App
    ports: 
      - '8000:8000'
    env_file:
      - .env
      
volumes:
  postgres_data: